name: Validate publiccode.yml

on:
  pull_request:
    paths:
      - publiccode.yml
  push:
    branches:
      - master
    paths:
      - publiccode.yml

jobs:
  publiccode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: italia/publiccode-parser-action@v1
